frontend:
  name: Frontend build
  runs-on: ubuntu-latest
  defaults:
    run:
      working-directory: frontend
  steps:
    - uses: actions/checkout@v4

    # Install Node (no pnpm cache here)
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Enable pnpm via Corepack (ships with Node 20)
    - run: corepack enable && corepack prepare pnpm@9 --activate
    - run: pnpm -v

    - run: pnpm install
    - run: pnpm build